{% set version = "2.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-basictrendline
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/basicTrendline_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/basicTrendline/basicTrendline_{{ version }}.tar.gz
  sha256: 11be56caab57b2a8f2e4d1a7803638050a215524271f36eae85a8c38eab60210

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-investr
    - r-scales
  run:
    - r-base
    - r-investr
    - r-scales

test:
  commands:
    - $R -e "library('basicTrendline')"           # [not win]
    - "\"%R%\" -e \"library('basicTrendline')\""  # [win]

about:
  home: https://github.com/PhDMeiwp/basicTrendline
  license: GPL-3.0-only
  summary: Plot, draw regression line and confidence interval, and show regression equation, R-square and P-value,  as simple as possible, by using different models ("line2P", "line3P", "log2P", "exp2P", "exp3P", "power2P", "power3P") built in the 'trendline()' function.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: basicTrendline
# Version: 2.0.3
# Date: 2018-07-26
# Title: Add Trendline and Confidence Interval of Basic Regression Models to Plot
# Authors@R: c( person("Weiping", "Mei",     email = "meiweipingg@163.com", role = c("aut", "cre", "cph"), comment = c(ORCID = "0000-0001-6400-9862")), person("Guangchuang", "Yu",     email = "guangchuangyu@gmail.com", role = c("aut"), comment = c(ORCID = "0000-0002-6485-8781")), person("Jiangshan", "Lai", role = c("ctb")), person("Qiang", "Rao",   role = "ctb"), person("Yu", "Umezawa",  role = "ctb") )
# Maintainer: Weiping Mei <meiweipingg@163.com>
# Description: Plot, draw regression line and confidence interval, and show regression equation, R-square and P-value,  as simple as possible, by using different models ("line2P", "line3P", "log2P", "exp2P", "exp3P", "power2P", "power3P") built in the 'trendline()' function.
# Depends: R (>= 2.1.0)
# Imports: graphics, stats, scales, investr
# BugReports: https://github.com/PhDMeiwp/basicTrendline/issues
# License: GPL-3
# URL: https://github.com/PhDMeiwp/basicTrendline
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-07-26 03:26:49 UTC; Unitcom
# Author: Weiping Mei [aut, cre, cph] (<https://orcid.org/0000-0001-6400-9862>), Guangchuang Yu [aut] (<https://orcid.org/0000-0002-6485-8781>), Jiangshan Lai [ctb], Qiang Rao [ctb], Yu Umezawa [ctb]
# Repository: CRAN
# Date/Publication: 2018-07-26 11:50:05 UTC
